import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    'getting-started',
    'schema',
    'api',
    'external-schemas',
    'examples',
    {
      type: 'category',
      label: 'Next.js Projects',
      items: [{type: 'autogenerated', dirName: 'nextjs-projects'}],
    },
  ],
};

export default sidebars;
